* Twister
Many webpages used dynamic loading so video source finding don't work with mpv
(youtube-dl) so I created this simple python script.

* Requirements
- Python3 
- Pip (pipenv)
- Selenium installed though pip / pipenv
- Chromedriver or Geckodriver
  - If you installed Chromedriver you need chromium / chorme and if Geckodriver
    you need firefox

* Installation
- On project folder run "python setup.py install" if you want global
  installation and "python setup.py install --user" if local.

* Why tool like this
I prefer watch something as I code and usually I have multi-head setup but
nowadays I use a lot my laptop with one monitor so browsers are quite
screenspace heavy tools for single monitor.

* Example way to use this tool
- Well install this tool (duh)
- Install newsboat
  - Add twist.moe rss to newsboat urls file
- Add to newsboat new macro "macro t set browser "twister %u"; open-in-browser ;
  set browser "elinks %u""
- Now you can use keyboard shortcut ", t" at news post position to open link
  with twister.
- Enjoy the show
